[versions]
kotlin = "2.1.10"
kotlin-serialization = "1.8.0"
mockk = "1.13.7"
junit-bom = "5.9.1"


[libraries]
kotlin-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlin-serialization" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlin-serialization-properties = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-properties", version.ref = "kotlin-serialization" }

mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-bom" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }


[plugins]
[bundles]