name: unit test
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    # build job
    build:
        # Runnerを指定
        runs-on: ubuntu-latest
        # Step
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: '11'
                  distribution: 'coretto'
                  cache: gradle

            - name: Build with Gradle
              run: ./gradlew test

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}